### ISSUE TITLE
Issues with windows version

### ISSUE THREAD

**Issue by AdamGauley** [12HuYang/GridFree#1]
**Describe the bug**
When I click segment on the windows app, it does not complete and so the program doesnt advance. 

**To Reproduce**
1. upload image
2. select clusters
3. click eSgment

**Expected behavior**
I would see the selected data for grain size

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This program looks great and I would love to use it. Let me know if you need anymore information.

**Comment by 12HuYang** [comment]
Hi Adam,

Thank you for the feedback. The advanced features, such as select areas to segment, are available for the Python implement version. 

Windows OS compiled version is under development and will be available soon.

Yang Hu
