### ISSUE TITLE
Error has happen in run the program

### ISSUE THREAD

**Issue by trunalkotadiya** [12HuYang/GridFree#2]
see error

while final step after installing all packages when try to run the command given by you it shows the following error

ImportError: cannot import name 'watershed' from 'skimage.morphology' (C:\Users\Tk\anaconda3\lib\site-packages\skimage\morphology\__init__.py)

**Additional context**

so i unable to open the program

**Comment by 12HuYang** [comment]
Please check your skimage package version, and make sure it is 0.17.2. 

The reason is watershed method is removed from the package in its later version. 0.17.2 is the one you can install under Python3.6.5 and still has the watershed method.
