### ISSUE TITLE
Window 11 cannot segment

### ISSUE THREAD

**Issue by pkxwonderr** [12HuYang/GridFree#4]
**Describe the bug**
After all the steps, when I click segment, the program has error 
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "tkinterGUI_nw.py", line 3441, in process
  File "tkinterGUI_nw.py", line 3033, in resegment
  File "tkinterGUI_nw.py", line 3236, in cal_xvalue
ZeroDivisionError: division by zero

**To Reproduce**
1. Upload image
2. PCs
3. Cluster => selected => Segment

**Expected behavior**
The program can segment and give output

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 11

**Additional context**
I want to learn about the code and tried to fix the problem myself but I cannot find the tkinterGUI_nw.py file in the folder download from dropbox (for Win10). Thank you for creating this program I think it is helpful and I would love to use it

**Comment by 12HuYang** [comment]
Make sure your python package is same as the repo suggests: [https://github.com/12HuYang/GridFree/blob/master/requirements.txt](https://github.com/12HuYang/GridFree/blob/master/requirements.txt)
And using Python version of 3.6.5

**Comment by pkxwonderr** [comment]
Thank you for your reply, I checked again and it was indeed my problem for not using Py 3.6.5. I switched to Py 3.6.5 and it works smoothly, thank you.
